# -*- coding: utf-8 -*-
"""
AlphaDesk PDF export service.

Converts analysis markdown reports into professionally styled HTML/PDF documents.
Uses WeasyPrint when available; callers should fall back to HTML + browser print.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional, Tuple

import markdown2

logger = logging.getLogger(__name__)

DISCLAIMER_ZH = (
    "本工具仅提供辅助分析，不构成投资建议。市场有风险，投资需谨慎，请独立判断并自担风险。"
)
DISCLAIMER_EN = (
    "This tool provides auxiliary analysis only and does not constitute investment advice. "
    "Markets involve risk — use at your own risk."
)


def _try_weasyprint_html_to_pdf(html: str) -> Optional[bytes]:
    try:
        from weasyprint import HTML  # type: ignore

        return HTML(string=html).write_pdf()
    except Exception as exc:  # noqa: BLE001
        logger.info("WeasyPrint unavailable or failed: %s", exc)
        return None


def build_report_html(
    *,
    title: str,
    subtitle: str,
    markdown_body: str,
    language: str = "zh",
    brand: str = "AlphaDesk · 阿尔法工作台",
) -> str:
    """Wrap markdown content in a print-ready HTML template."""
    body_html = markdown2.markdown(
        markdown_body,
        extras=["tables", "fenced-code-blocks", "strike", "task_list"],
    )
    disclaimer = DISCLAIMER_ZH if language == "zh" else DISCLAIMER_EN
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""<!DOCTYPE html>
<html lang="{language}">
<head>
  <meta charset="utf-8" />
  <title>{title}</title>
  <style>
    @page {{
      size: A4;
      margin: 18mm 16mm 20mm 16mm;
      @bottom-center {{
        content: "AlphaDesk · {generated}";
        font-size: 9px;
        color: #94a3b8;
      }}
    }}
    * {{ box-sizing: border-box; }}
    body {{
      font-family: "PingFang SC", "Microsoft YaHei", "SF Pro Display", system-ui, sans-serif;
      color: #0f172a;
      line-height: 1.65;
      font-size: 11pt;
      margin: 0;
      background: #fff;
    }}
    .header {{
      border-bottom: 2px solid #0ea5e9;
      padding-bottom: 14px;
      margin-bottom: 20px;
    }}
    .brand {{
      font-size: 10px;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      color: #0ea5e9;
      font-weight: 600;
    }}
    h1.doc-title {{
      font-size: 22pt;
      margin: 6px 0 4px;
      color: #0f172a;
    }}
    .subtitle {{
      color: #64748b;
      font-size: 11pt;
    }}
    .disclaimer {{
      background: #fffbeb;
      border: 1px solid #fcd34d;
      border-radius: 8px;
      padding: 10px 12px;
      font-size: 9pt;
      color: #92400e;
      margin-bottom: 18px;
    }}
    .content h1, .content h2, .content h3 {{
      color: #0369a1;
      margin-top: 1.2em;
    }}
    .content table {{
      width: 100%;
      border-collapse: collapse;
      margin: 12px 0;
      font-size: 10pt;
    }}
    .content th, .content td {{
      border: 1px solid #e2e8f0;
      padding: 6px 8px;
      text-align: left;
    }}
    .content th {{ background: #f1f5f9; }}
    .content code {{
      background: #f1f5f9;
      padding: 1px 4px;
      border-radius: 3px;
      font-size: 9pt;
    }}
    .content blockquote {{
      border-left: 3px solid #0ea5e9;
      margin: 12px 0;
      padding: 4px 12px;
      color: #475569;
      background: #f8fafc;
    }}
    .footer {{
      margin-top: 24px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      font-size: 9pt;
      color: #94a3b8;
      text-align: center;
    }}
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">{brand}</div>
    <h1 class="doc-title">{title}</h1>
    <div class="subtitle">{subtitle}</div>
  </div>
  <div class="disclaimer">⚠️ {disclaimer}</div>
  <div class="content">{body_html}</div>
  <div class="footer">Generated by AlphaDesk · {generated}</div>
</body>
</html>"""


def export_markdown_to_pdf(
    markdown_body: str,
    *,
    title: str,
    subtitle: str,
    language: str = "zh",
) -> Tuple[Optional[bytes], str]:
    """
    Convert markdown to PDF bytes and HTML fallback.

    Returns (pdf_bytes_or_none, html_string).
    """
    html = build_report_html(
        title=title,
        subtitle=subtitle,
        markdown_body=markdown_body,
        language=language,
    )
    pdf_bytes = _try_weasyprint_html_to_pdf(html)
    return pdf_bytes, html